version: "3.9"
services:
  web:
    build: .
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/elasticsearch_exam
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
  elasticsearch:
    build: ./docker/es
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - xpack.monitoring.collection.enabled=false
      - xpack.security.enabled=false
      - network.host=elasticsearch
      - "ES_JAVA_OPTS=-Xms512M -Xmx512M"
    ports:
      - "9200:9200"
  kibana:
    image: docker.elastic.co/kibana/kibana:8.2.3
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
  redis:
    image: redis:latest
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
  sidekiq:
    build: .
    command: bundle exec sidekiq -C config/sidekiq.yml
    volumes:
      - .:/elasticsearch_exam
    depends_on:
      - redis
    environment:
      REDIS_URL: redis://redis:6379
